export const ProjectsCategoryLookupTable = {
  "시스템/네트워크": "SYSTEM_NETWORK",
  "웹/애플리케이션": "WEB_APPLICATION",
  컴퓨터비전: "COMPUTER_VISION",
  "보안/소프트웨어공학": "SECURITY_SOFTWARE_ENGINEERING",
  "AI/머신러닝": "AI_MACHINE_LEARNING",
  자연어처리: "NATURAL_LANGUAGE_PROCESSING",
  빅데이터분석: "BIG_DATA_ANALYSIS",
  "인터랙션/증강현실": "INTERACTION_AUGMENTED_REALITY",
  SYSTEM_NETWORK: "시스템/네트워크",
  WEB_APPLICATION: "웹/애플리케이션",
  COMPUTER_VISION: "컴퓨터비전",
  SECURITY_SOFTWARE_ENGINEERING: "보안/소프트웨어공학",
  AI_MACHINE_LEARNING: "AI/머신러닝",
  NATURAL_LANGUAGE_PROCESSING: "자연어처리",
  BIG_DATA_ANALYSIS: "빅데이터분석",
  INTERACTION_AUGMENTED_REALITY: "인터랙션/증강현실",
};
